project:
  type: website

website:
  title: "ISSS608_VAA_GROUP15"
  navbar:
    logo: "images/icon.png"
    pinned: true
    align: left
    max-height: 100px
    left: 
    - href: index.qmd
      text: Home
    - href: Proposal.qmd
      text: Proposal
    - href: UserGuide.qmd
      text: User Guide   
    - href: "http://isss608vaa-2023apr-group15.shinyapps.io/Group15APP "
      text: APP
    - href: Poster.qmd
      text: Poster
    right: 
    - href: about.qmd
      text: About
      
format:
  html:
    code-fold: true
    code-summary: "show the code"
    theme: flatly
    css: styles.css
    toc: true
execute: 
  echo: true
  eval: true
  warning: false
  
editor: visual
