project:
  type: website

website:
  title: "ISSS608_VAA_GROUP15"
  navbar:
    logo: "images/icon.png"
    pinned: true
    align: left
    max-height: 100px
    left: 
    - href: index.qmd
      text: Home
    - href: Proposal.qmd
      text: Proposal
    - href: UserGuide.qmd
      text: User Guide   
    - href: "https://3vm3r5-da-huo.shinyapps.io/Visual-Project/?_ga=2.139833585.395284405.1680390288-1164590008.1680258801"
      text: APP
    - href: Poster.qmd
      text: Poster
    right: 
    - href: about.qmd
      text: About
      
format:
  html:
    code-fold: true
    code-summary: "show the code"
    theme: flatly
    css: styles.css
    toc: true
execute: 
  echo: true
  eval: true
  warning: false
  
editor: visual
